name: Grafana Loki SysLog

on:
  push:
    branches: [ develop, main ]
    tags: ['v*.*.*']

env:
  GCR_IMAGE: asia.gcr.io/evermed-devops-prod/devops/grafana-demo
  GIT_DEPLOY: its-knowledge-sharing/grafana-demo-deployment.git

jobs:

  build:    
    runs-on: self-hosted #This repository need to be private, otherwise runner will not pick the job (security reason)

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build Application
      id: build-application
      run: |
        export PATH="/utils:/scripts:${PATH}"
        run-prepare.bash
        run-docker-push.bash ${GCR_IMAGE} $(pwd)

  deploy:    
    runs-on: self-hosted #This repository need to be private, otherwise runner will not pick the job (security reason)

    steps:
    - name: Deploy Application
      needs: build-application
      id: deploy-application
      run: |
        export PATH="/utils:/scripts:${PATH}"
        run-prepare.bash
        run-deployment.bash ${GIT_DEPLOY} AUTO DIRECT
