name: Grafana Loki SysLog

on:
  push:
    branches: [ develop, main ]
    tags: ['v*.*.*']

env:
  GCR_IMAGE: asia.gcr.io/evermed-devops-prod/devops/grafana-demo
  GIT_DEPLOY: its-knowledge-sharing/grafana-demo-deployment.git

jobs:

  build:    
    runs-on: self-hosted #This repository need to be private, otherwise runner will not pick the job (security reason)
    if: contains('refs/heads/develop|refs/heads/main|refs/tags/', github.ref)
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build Application
      id: build-application
      run: |
        export PATH="/utils:/scripts:${PATH}" # TODO : Move this to docker image
        run-prepare.bash
        run-docker-push.bash ${GCR_IMAGE} $(pwd)
      #TODO : Transfer state between jobs

  deploy-nonprod:
    runs-on: self-hosted
    if: contains('refs/heads/develop', github.ref)
    needs: build
    steps:
    - name: Deploy Application      
      id: deploy-application
      run: |
        export PATH="/utils:/scripts:${PATH}"
        run-prepare.bash
        run-deployment.bash ${GIT_DEPLOY} AUTO DIRECT

  deploy-prod:
    runs-on: self-hosted
    if: contains('refs/heads/main', github.ref)
    needs: build
    steps:
    - name: Deploy Application      
      id: deploy-application
      run: |
        export PATH="/utils:/scripts:${PATH}"
        run-prepare.bash
        run-deployment.bash ${GIT_DEPLOY} AUTO DIRECT
