name: Grafana Loki SysLog

on:
  push:
    branches: [ develop, main ]
    tags: ['v*.*.*']

env:
  ENV_GCR_IMAGE: gcr.io/its-artifact-commons/grafana-demo
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build-and-deploy:    
    runs-on: self-hosted #This repository need to be private, otherwise runner will not pick the job (security reason)

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Test running script
      id: test2
      run: |
        export PATH="/utils:/scripts:${PATH}"
        run-prepare.bash
        run-docker-push.bash asia.gcr.io/evermed-devops-prod/devops/edh-grafana $(pwd)
